# -*- coding: utf-8 -*-
"""
Created on Wed Jul 28 13:05:24 2021

@author: yeji
"""

file_dir = "C:/Users/yuyae/Downloads"
#%% 1 Counting DNA Nucleotides
seq= """TATGTCCCATAATGTATTTAAACACCTACTATACTGCATCTAGTCGTTCGAGGAAATCCGTCGTCCTTAC
CGTGTCTCGGCGTCCGTCGATCAGTAATAGACTGCCTTCGTTCCTCTGACGTTGTTCATTGAGTGCGAGCCCCGTTCG
CAATACCACACTAGTCAGCGTTGCGCATATTCGAACTTGGCGCCTTCAGCGTGCGCCTAAGGTCTGCAAAGGAGGCTC
CGCAAGAGCGATGTTGGATTCGTTTGTAACATAAGTCGAGGACGTTTATCGTATAACTTTTTGCAAGAAGTGGCACGT
AGGGACGGTGATCGCGGTCTAGGTGAACAATACAAATGAATTTTGTGACAACTAAGTGCCACAAGTAGTTCGGACGAG
AGTAGCAGTGGCTCGCTCTTGGTTAGACAAAGAAGGAAGAGGTCCATAATAGTATTAAATGATATCGCCAGTGAAATC
CGCCACCGGACGAATAGCAGCCAGCCCAAGCAGACAAGGTTCGGTCGACTAGGCCCAGTACCGCCGTCTAGTTACACG
TGTGAAGATACGGAATGTCGTAGCTGCACGGAGCGGGAGATTGCATCATGAAGGGCGCTACGCGACGTATGTATATGG
TTCGCTACTATGTGCAAGCCTCCAGCGGACACTAACAGCAGTGCATGTCATGACCCGCATATTATGATGCGTAACTGA
CGAGTGCTCACGAGGCGGGTATGGTGTCAGCATGTCCCGCATTTGCTTAGTCGCTGTGGACACAGCACGTGACGTGAC
GCGAATTTTATGGAGCCGCCCAAGCTTGAAGTAGACCCTTCTGCTGTTTAATCAGTATCTGGTCCTGTGGGAGCACTC
CTTGGTGCGTATAAGTACAAAGGTCTCTTTCGTGTGCTCAAGGGGGTATATAGTTGTCGTATCGTTAGCGCGAGCCAC
TGGGCTTCATCGACGTAACTTGTTGTGGGGAGGCGCCCGTTAACGACCAGG"""

for i in ["A","C","G","T"]:
    print(seq.count(i), end=" " )

#%% 2 Transcribing DNA into RNA
dna='''GGAACCCCTGCGCGCGGACATGAATGTCCTGTCATAAGGTAGTTTTTAGCGGCTGGGTGTAGTGTTGCACC
ACGAACCGTTGCGATCTATCTGTCGTACTTGCCGCGGAGAAAAGGGGGGTTGTGGCTCCGAGCTCTAGATCCCGTACG
GTTGTCAACTTGCGTGACCGAGGTCTAGGGGTCCATTTGACTTCGTCTTGACCATGGTAGCTAACGAGGAACATTCTT
AGCTGTAACGTACTTTCAGGGACTCGACCGGCCCAAGATCATCACGAACTGAGCGGCAGCCTTCAACGTCATGGATAA
TATCCCGCCTCCTGATGTACTCTGCTGTTCTGCCTTAGTACACAAGCGGTGACGAAACTCCTGTGGGTCAATCCTAGG
AACTTCTATAAACCCGAGGGGAAAGTCGCACTAATTTCATTTCAATCCACTAGCTATTTCGAGTGCTCCATGGATAAA
CGCCTGTGGGATATCAATAGGGAACAGTTCAGTGTACAGATACGCATTGCTGCCTGCGGCTAGCCATCTGGATTTCAA
CCCAACGTTGACGTGTCCACATCAAGGTGCTTCCTTCTCTACACCTGCGTCAAACGACCCTCGGCAAGCAGGGAGAGT
TTCAGACCCTGCCGAAGGATAGCGAAGTGATCGAGCCTATTTCTTGTGTAAAGGATCGTAGGGGCGTCTGGCCGATTC
TATAGAACAGTTCTTAGTTAAAAGCAATATCACCGTAAATTTAGAGCATGGTCTGCGCCCCGCCGCTAAGACGCCATC
CTAACCTATGCCCCTTTGTTTCTATACATTTGGTTCCATGTAGTAGGGCGAACATATTCGCTCGCGTAAGCGCTTTTC
GGTACGTAGGTCCGGAACGGTTATCGCTTGAGGACCCACAAACGCTTCCTCTCTTCTATTAAATGCCGCGAGTCGCGT
ACCCGATACACCA'''

dna=dna.replace("T","U")
print(dna)

#%% 3 Complementing a strand of DNA
file = open("C:/Users/yuyae/Downloads/rosalind_revc.txt",'r')
DNA_seq = file.read().strip()
file.close()

DNA_seq = DNA_seq.lower()
DNA_seq = DNA_seq.replace('a','T')
DNA_seq = DNA_seq.replace('c','G')
DNA_seq = DNA_seq.replace('t','A')
DNA_seq = DNA_seq.replace('g','C')
print(DNA_seq[::-1])
